# Generated by Django 3.2.9 on 2022-02-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0004_alter_blogmodel_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
