# Generated by Django 3.2.9 on 2022-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0006_auto_20220227_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='liked',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='liked',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
